epi_exchanges_homepage:
    path:     /exchange-rates
    defaults: { _controller: EpiExchangesBundle:Default:index }
epi_exchanges_view:
    path:     /exchange-rates/view/{code}
    defaults: { _controller: EpiExchangesBundle:Default:view }
